version: 0.2  
phases:  
  install:
    runtime-versions:
        nodejs: 12
  pre_build:  
    commands:  
    #- npm install  
      - echo "pre_build complete"
  build:  
    commands:  
      - echo "build complete" 
artifacts:  
  files:  
    - '**/*'
